### ISSUE TITLE
Extend schema to contain table name, and migrate cost model's ColumnRef property usage to schema

### ISSUE THREAD

**Issue by jurplel** [cmu-db/optd-original#126]
From Chi:

> yes we should do that, feel free to create an issue...
> this is so-called "column name inference"
> assign a name for unnamed columns, and use user-specified names for projections
> and for the top-level node, if we have physical property implemented, it will always be a gather node
> unless all plan nodes are singleton

ColumnRef and Schema seem to have a lot of purpose overlap, I think that we can merge their functionality together.

**Comment by jurplel** [comment]
After reading more into `ColumnRef`, I am not as sure that it is redundant... Seems like a lot going on

**Comment by skyzh** [comment]
yes, they are all column-level properties; but they are different -- schema is more focused on column type + name, while column ref indicates how the column is computed (which will then be used by the cost model to derive the cost)

**Comment by skyzh** [comment]
with https://github.com/cmu-db/optd/issues/202, I feel the final state of this property will be like:

* after aggregation: we will get something like `Distinct(ColumnRef)`
* after projection, i.e., select v1 + 1 from table: we will get something like `Add(v1, 1)`
* after join, we will get something like `Correlated(X, Y, original_column_ref)`

so it could be more complex that what it is right now
