### ISSUE TITLE
Investigate Switching TestOptimizer to use Cascades (and whether or not we want to)

### ISSUE THREAD

**Issue by jurplel** [cmu-db/optd-original#152]
Currently it uses the heuristic optimizer. It seems that to use the cascades optimizer, we might need to introduce a more advanced dummy cost model. It might also be the case that we want to just keep testing on the heuristic optimizer.

See #140 for context.

**Comment by AveryQi115** [comment]
I think we can use two phase now, no need for using heuristic rules to test cascades. Some rules are not well designed for cascades and jignesh agrees on that too.

**Comment by jurplel** [comment]
Ok, I'll just close this issue for now then. Thanks for your feedback!
