### ISSUE TITLE
Decouple datafusion's logical optimization/conversion

### ISSUE THREAD

**Issue by jurplel** [cmu-db/optd-original#45]
Remove:
```rs
        let batches = df.collect().await?;
```
from `datafusion-optd-cli/src/exec.rs`

because it will internally run `datafusion`'s logical optimizer. We should try to call the *other* `collect` function instead, after running our own optimizer and converting the `optd` plan into `datafusion`'s (`impl ExecutionPlan`). This will allow us to run our end-to-end optimized query on `datafusion`.

**Comment by yliang412** [comment]
I'm thinking about waiting on this: https://github.com/apache/arrow-datafusion/pull/9063. With this, we can place our optimizer in session state instead.

**Comment by yliang412** [comment]
- [ ] temporary solution (clear rules, max_pass=0)
- [ ] extension context in Datafusion
- [ ] long term: systematic state persistence across sessions
