### ISSUE TITLE
Produce metadata along with RelNode

### ISSUE THREAD

**Issue by yliang412** [cmu-db/optd-original#65]
- add group id metadata so DAG can be identified
- remove physical collector from `optd-core`

**Comment by Gun9niR** [comment]
I thought physical collector is in DF bridge?

**Comment by yliang412** [comment]
> I thought physical collector is in DF bridge?

Yes, but right now it relies on `optd-core` to take in an `on_produce` callback to inject the collector. As a result of producing the metadata in #83, we will remove the dependency.
