### ISSUE TITLE
Bug: projection pull up rule does not work when the join has multiple predicates

### ISSUE THREAD

**Issue by Gun9niR** [cmu-db/optd-original#79]
When there are multiple join predicates, they are stored as `LogOp(And)`

https://github.com/cmu-db/optd/blob/ad371490b796d6734cc54a609ed0abaf4242c0fe/optd-datafusion-bridge/src/into_optd.rs#L299-L305

But this case is not handled in the projection pull up rule.

https://github.com/cmu-db/optd/blob/755db923854eaae2b7bb3edbf04034ca2ab298e8/optd-datafusion-repr/src/rules/joins.rs#L330-L342

Here, it seems we assume `cond` is a `BinOpExpr` (so that its children are aways `Expr`), but for `LogOp` its child is a `ExprList`, whose type is `List` which is not an expression. That's why the `unwrap()` on line 335 panics.

We can hard code this scenario, or categorize `OptRelNodeTyp::List` into expression (but I'm not 100% sure whether is only used to store expression).

**Comment by skyzh** [comment]
Does it make sense to make ExprList an expression?

**Comment by skyzh** [comment]
Or we need the helper function to rewrite both list and expr.

**Comment by skyzh** [comment]
Or can we have ExprList (for projection list) and ExprVarChildren separately? (Need to remove list_typ from RelNodeTyp)

**Comment by AveryQi115** [comment]
Solved by this pr https://github.com/cmu-db/optd/pull/108 as LogOpExpr now takes vec<Expr> as its children.
